name: Create Bastion

on:
  workflow_dispatch:
    inputs:
      aws_account:
        description: "AWS Account to use"
        required: true
        type: choice
        options:
          - alexander-test
          - eliza-dev
          - emir-production

      bucket_name:
        description: "S3 bucket name for Terraform state"
        required: true
        type: string

      bucket_region:
        description: "S3 bucket region"
        required: true
        type: choice
        options:
          - us-east-1
          - us-east-2
          - us-west-1
          - us-west-2

      bastion_instance_region:
        description: "Bastion instance region"
        required: true
        type: choice
        options:
          - ca-central-1
          - us-east-1
          - us-west-2
        default: "ca-central-1"

      bastion_instance_key:
        description: "Bastion instance key pair name"
        required: true
        type: string
        default: "bastion-key"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.bastion_instance_region }}

    steps:
      - name: Checkout Current Repository (ProjectNagiosWorkflows)
        uses: actions/checkout@v4
        with:
          path: ProjectNagiosWorkflows

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.12.2"

      # Configure AWS credentials dynamically based on selected account
      - name: Configure AWS Credentials (Eliza Dev)
        if: ${{ inputs.aws_account == 'eliza-dev' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: ${{ inputs.bastion_instance_region }}

      - name: Configure AWS Credentials (Alexander Test)
        if: ${{ inputs.aws_account == 'alexander-test' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_TEST }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_TEST }}
          aws-region: ${{ inputs.bastion_instance_region }}

      - name: Configure AWS Credentials (Emir Production)
        if: ${{ inputs.aws_account == 'emir-production' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PRODUCTION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PRODUCTION }}
          aws-region: ${{ inputs.bastion_instance_region }}

      # Terraform Init & Apply
      - name: Terraform Init
        working-directory: ProjectNagiosWorkflows/terraform/bastion
        run: terraform init -backend-config="bucket=${{ inputs.bucket_name }}" -backend-config="region=${{ inputs.bucket_region }}"

      - name: Terraform Apply
        working-directory: ProjectNagiosWorkflows/terraform/bastion
        run: terraform apply -auto-approve -var "key_name=${{ inputs.bastion_instance_key }}" -var "region=${{ inputs.bastion_instance_region }}"
