name: Build Nagios AMI Image

on:
  workflow_dispatch:
    inputs:
      region:
        description: "AWS region to build AMI"
        required: true
        type: choice
        options:
          - ca-central-1
          - us-east-1
          - us-east-2
          - us-west-1
          - us-west-2
      aws_account:
        description: "AWS Account to use"
        required: true
        type: choice
        options:
          - alexander-test
          - eliza-dev
          - emir-production
          
jobs:
  build-image:
    runs-on: ubuntu-latest
    environment: ${{ inputs.region }}
    steps:
      - name: Checkout Current Repository (ProjectNagiosWorkflows)
        uses: actions/checkout@v4
        with:
          path: ProjectNagiosWorkflows

      - name: Checkout Private Repository (ProjectNagios)
        uses: actions/checkout@v4
        with:
          repository: "DevOps-Triumvirat/ProjectNagios"
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          path: ProjectNagios

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "1.10.0"

      - name: Configure AWS Credentials (Alexander Test)
        if: ${{ inputs.aws_account == 'alexander-test' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_TEST }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_TEST }}
          aws-region: ${{ inputs.region }}

      - name: Configure AWS Credentials (Eliza Dev)
        if: ${{ inputs.aws_account == 'eliza-dev' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: ${{ inputs.region }}

      - name: Configure AWS Credentials (Emir Production)
        if: ${{ inputs.aws_account == 'emir-production' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PRODUCTION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PRODUCTION }}
          aws-region: ${{ inputs.region }}

      - name: Packer Init
        working-directory: ProjectNagios/Packer
        run: packer init server_nagios.pkr.hcl

      - name: Packer Validate
        working-directory: ProjectNagios/Packer
        run: packer validate server_nagios.pkr.hcl

      - name: Packer Build
        working-directory: ProjectNagios/Packer
        run: |
          echo "Starting Packer build for Nagios AMI..."
          
          packer build \
            -var "region=${{ inputs.region }}" \
            server_nagios.pkr.hcl

      - name: Get AMI Information to AWS
        working-directory: ProjectNagios/Packer
        run: |
          echo "Packer build completed successfully!"
          
          AMI_ID=$(aws ec2 describe-images \
            --region ${{ inputs.region }} \
            --owners self \
            --filters "Name=name,Values=Nagios-ami*" \
            --query 'Images | sort_by(@, &CreationDate) | [-1].ImageId' \
            --output text)
          
          if [ "$AMI_ID" != "None" ] && [ "$AMI_ID" != "" ]; then
            echo "Created AMI ID: $AMI_ID"
            aws ec2 describe-images \
              --region ${{ inputs.region }} \
              --image-ids $AMI_ID \
              --query 'Images[0].{Name:Name,ImageId:ImageId,State:State,CreationDate:CreationDate}' \
              --output table
          else
            echo "Warning: Could not retrieve AMI information"
          fi
