name: Terraform Deploy

on:
  workflow_dispatch:
    inputs:
      region:
        description: "AWS region"
        required: true
        default: "us-east-1"
      aws_account:
        description: "Which AWS account to deploy to (eliza-dev, alexander-test, emir-production)"
        required: true
        default: "eliza-dev"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.region }}

    steps:
      - name: Checkout Current Repository (ProjectNagiosWorkflows)
        uses: actions/checkout@v4
        with:
          path: ProjectNagiosWorkflows

      - name: Checkout Private Repository (ProjectNagios)
        uses: actions/checkout@v4
        with:
          repository: "DevOps-Triumvirat/ProjectNagios"
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          path: ProjectNagios

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.12.2"

      # AWS Credentials per account
      - name: Configure AWS Credentials for Dev Account
        if: inputs.aws_account == 'eliza-dev'
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: ${{ inputs.region }}

      - name: Configure AWS Credentials for Alexander Test
        if: inputs.aws_account == 'alexander-test'
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_TEST }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_TEST }}
          aws-region: ${{ inputs.region }}

      - name: Configure AWS Credentials for Emir Production
        if: inputs.aws_account == 'emir-production'
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PRODUCTION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PRODUCTION }}
          aws-region: ${{ inputs.region }}

      - name: Create terraform.tfvars from environment secret and inputs
        working-directory: ProjectNagios/Terraform/Nagios
        run: |
          # Mask the tfvars secret in logs
          echo "::add-mask::${{ secrets.TERRAFORM_TFVARS }}"

          # Write secret to terraform.tfvars (supports multiline)
          printf "%s\n" "${{ secrets.TERRAFORM_TFVARS }}" > terraform.tfvars

          # Append runtime values from inputs
          echo "aws_region = \"${{ inputs.region }}\"" >> terraform.tfvars
          echo "aws_account = \"${{ inputs.aws_account }}\"" >> terraform.tfvars

      - name: Terraform Init
        working-directory: ProjectNagios/Terraform/Nagios
        run: terraform init

      - name: Terraform Plan
        working-directory: ProjectNagios/Terraform/Nagios
        run: terraform plan -input=false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: ProjectNagios/Terraform/Nagios
        run: terraform apply -auto-approve -input=false
